//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartEngineer.ServiceClient.Services {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="JiraServiceForENGSupp.IJiraServiceForENGSupp")]
    public interface IJiraServiceForENGSupp {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJiraServiceForENGSupp/GetIssuesByLabelList", ReplyAction="http://tempuri.org/IJiraServiceForENGSupp/GetIssuesByLabelListResponse")]
        void GetIssuesByLabelList(string[] labelList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJiraServiceForENGSupp/GetIssuesByLabelList", ReplyAction="http://tempuri.org/IJiraServiceForENGSupp/GetIssuesByLabelListResponse")]
        System.Threading.Tasks.Task GetIssuesByLabelListAsync(string[] labelList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJiraServiceForENGSupp/GetIssuesByStatusList", ReplyAction="http://tempuri.org/IJiraServiceForENGSupp/GetIssuesByStatusListResponse")]
        void GetIssuesByStatusList(string[] statusList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJiraServiceForENGSupp/GetIssuesByStatusList", ReplyAction="http://tempuri.org/IJiraServiceForENGSupp/GetIssuesByStatusListResponse")]
        System.Threading.Tasks.Task GetIssuesByStatusListAsync(string[] statusList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJiraServiceForENGSupp/GetIssuesBySalesforceIDList", ReplyAction="http://tempuri.org/IJiraServiceForENGSupp/GetIssuesBySalesforceIDListResponse")]
        void GetIssuesBySalesforceIDList(string[] caseIDList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJiraServiceForENGSupp/GetIssuesBySalesforceIDList", ReplyAction="http://tempuri.org/IJiraServiceForENGSupp/GetIssuesBySalesforceIDListResponse")]
        System.Threading.Tasks.Task GetIssuesBySalesforceIDListAsync(string[] caseIDList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJiraServiceForENGSupp/ImportSalesforceCases", ReplyAction="http://tempuri.org/IJiraServiceForENGSupp/ImportSalesforceCasesResponse")]
        void ImportSalesforceCases(string[] caseIDList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJiraServiceForENGSupp/ImportSalesforceCases", ReplyAction="http://tempuri.org/IJiraServiceForENGSupp/ImportSalesforceCasesResponse")]
        System.Threading.Tasks.Task ImportSalesforceCasesAsync(string[] caseIDList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJiraServiceForENGSupp/UpdateSalesforceCases", ReplyAction="http://tempuri.org/IJiraServiceForENGSupp/UpdateSalesforceCasesResponse")]
        void UpdateSalesforceCases(string[] caseIDList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJiraServiceForENGSupp/UpdateSalesforceCases", ReplyAction="http://tempuri.org/IJiraServiceForENGSupp/UpdateSalesforceCasesResponse")]
        System.Threading.Tasks.Task UpdateSalesforceCasesAsync(string[] caseIDList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJiraServiceForENGSupp/ImportSalesforceCaseComments", ReplyAction="http://tempuri.org/IJiraServiceForENGSupp/ImportSalesforceCaseCommentsResponse")]
        void ImportSalesforceCaseComments(string[] caseIDList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJiraServiceForENGSupp/ImportSalesforceCaseComments", ReplyAction="http://tempuri.org/IJiraServiceForENGSupp/ImportSalesforceCaseCommentsResponse")]
        System.Threading.Tasks.Task ImportSalesforceCaseCommentsAsync(string[] caseIDList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJiraServiceForENGSupp/UpdateJiraIssueStatusForSalesforceIDLis" +
            "t", ReplyAction="http://tempuri.org/IJiraServiceForENGSupp/UpdateJiraIssueStatusForSalesforceIDLis" +
            "tResponse")]
        void UpdateJiraIssueStatusForSalesforceIDList(string[] caseIDList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJiraServiceForENGSupp/UpdateJiraIssueStatusForSalesforceIDLis" +
            "t", ReplyAction="http://tempuri.org/IJiraServiceForENGSupp/UpdateJiraIssueStatusForSalesforceIDLis" +
            "tResponse")]
        System.Threading.Tasks.Task UpdateJiraIssueStatusForSalesforceIDListAsync(string[] caseIDList);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IJiraServiceForENGSuppChannel : SmartEngineer.ServiceClient.Services.IJiraServiceForENGSupp, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class JiraServiceForENGSuppClient : System.ServiceModel.ClientBase<SmartEngineer.ServiceClient.Services.IJiraServiceForENGSupp>, SmartEngineer.ServiceClient.Services.IJiraServiceForENGSupp {
        
        public JiraServiceForENGSuppClient() {
        }
        
        public JiraServiceForENGSuppClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public JiraServiceForENGSuppClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JiraServiceForENGSuppClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JiraServiceForENGSuppClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void GetIssuesByLabelList(string[] labelList) {
            base.Channel.GetIssuesByLabelList(labelList);
        }
        
        public System.Threading.Tasks.Task GetIssuesByLabelListAsync(string[] labelList) {
            return base.Channel.GetIssuesByLabelListAsync(labelList);
        }
        
        public void GetIssuesByStatusList(string[] statusList) {
            base.Channel.GetIssuesByStatusList(statusList);
        }
        
        public System.Threading.Tasks.Task GetIssuesByStatusListAsync(string[] statusList) {
            return base.Channel.GetIssuesByStatusListAsync(statusList);
        }
        
        public void GetIssuesBySalesforceIDList(string[] caseIDList) {
            base.Channel.GetIssuesBySalesforceIDList(caseIDList);
        }
        
        public System.Threading.Tasks.Task GetIssuesBySalesforceIDListAsync(string[] caseIDList) {
            return base.Channel.GetIssuesBySalesforceIDListAsync(caseIDList);
        }
        
        public void ImportSalesforceCases(string[] caseIDList) {
            base.Channel.ImportSalesforceCases(caseIDList);
        }
        
        public System.Threading.Tasks.Task ImportSalesforceCasesAsync(string[] caseIDList) {
            return base.Channel.ImportSalesforceCasesAsync(caseIDList);
        }
        
        public void UpdateSalesforceCases(string[] caseIDList) {
            base.Channel.UpdateSalesforceCases(caseIDList);
        }
        
        public System.Threading.Tasks.Task UpdateSalesforceCasesAsync(string[] caseIDList) {
            return base.Channel.UpdateSalesforceCasesAsync(caseIDList);
        }
        
        public void ImportSalesforceCaseComments(string[] caseIDList) {
            base.Channel.ImportSalesforceCaseComments(caseIDList);
        }
        
        public System.Threading.Tasks.Task ImportSalesforceCaseCommentsAsync(string[] caseIDList) {
            return base.Channel.ImportSalesforceCaseCommentsAsync(caseIDList);
        }
        
        public void UpdateJiraIssueStatusForSalesforceIDList(string[] caseIDList) {
            base.Channel.UpdateJiraIssueStatusForSalesforceIDList(caseIDList);
        }
        
        public System.Threading.Tasks.Task UpdateJiraIssueStatusForSalesforceIDListAsync(string[] caseIDList) {
            return base.Channel.UpdateJiraIssueStatusForSalesforceIDListAsync(caseIDList);
        }
    }
}
