//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartEngineer.ServiceClient.JiraServiceForDatabase {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="JiraServiceForDatabase.IJiraServiceForDatabase")]
    public interface IJiraServiceForDatabase {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJiraServiceForDatabase/DoWork", ReplyAction="http://tempuri.org/IJiraServiceForDatabase/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJiraServiceForDatabase/DoWork", ReplyAction="http://tempuri.org/IJiraServiceForDatabase/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IJiraServiceForDatabaseChannel : SmartEngineer.ServiceClient.JiraServiceForDatabase.IJiraServiceForDatabase, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class JiraServiceForDatabaseClient : System.ServiceModel.ClientBase<SmartEngineer.ServiceClient.JiraServiceForDatabase.IJiraServiceForDatabase>, SmartEngineer.ServiceClient.JiraServiceForDatabase.IJiraServiceForDatabase {
        
        public JiraServiceForDatabaseClient() {
        }
        
        public JiraServiceForDatabaseClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public JiraServiceForDatabaseClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JiraServiceForDatabaseClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JiraServiceForDatabaseClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
    }
}
